version: '3.1'

services:
  mysql:
    image: mysql:8
    env_file:
      - ./server/.env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

  # server:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   env_file:
  #     - ./server/.env
  #   ports:
  #     - "${APP_PORT:-55000}:55000"
  #   depends_on:
  #     - mysql
  #   volumes:
  #     - ./server:/usr/src/app
