version: '3.1'

services:
  odoo:
    image: odoo:17
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./data/web:/var/lib/odoo
      - ./data/config:/etc/odoo
      - ./data/addons:/mnt/extra-addons
      
  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
